---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplefrontend
  namespace: minikube-demo-samplefrontend
  labels:
    app.kubernetes.io/version: '1'
    app: samplefrontend
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: samplefrontend
      app.kubernetes.io/instance: samplefrontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: samplefrontend
        app.kubernetes.io/instance: samplefrontend
    spec:
      restartPolicy: Always
      containers:
        - name: samplefrontend
          image: hostmachine:5000/minikube-demo_samplefrontend:latest
          imagePullPolicy: Always
