---
apiVersion: v1
kind: Service
metadata:
  name: samplefrontend
  namespace: minikube-demo-samplefrontend
  labels:
    app.kubernetes.io/version: '1'
    app: samplefrontend
spec:
  selector:
    app: samplefrontend
    app.kubernetes.io/instance: samplefrontend
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
