---
apiVersion: v1
kind: Service
metadata:
  name: samplebackend
  namespace: minikube-demo-samplebackend
  labels:
    app.kubernetes.io/version: '1'
    app: samplebackend
spec:
  selector:
    app: samplebackend
    app.kubernetes.io/instance: samplebackend
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 7000
